# Generated by Django 5.2.8 on 2025-11-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_lang', models.CharField(max_length=32)),
                ('target_lang', models.CharField(max_length=32)),
                ('previous_code', models.TextField(blank=True)),
                ('feedback_text', models.TextField()),
                ('refined_code', models.TextField(blank=True)),
            ],
        ),
    ]
